### ISSUE TITLE
iputils-ping addition

### ISSUE THREAD

**Issue by ericutah** [borrougagnou/Firefox-GNS3#1]
Could iputils-ping be added to the appliance on the next build?  It's possible to run apt and install it manually, but it's not persistent between reboots.  Deps are libcap2-bin and libpam-cap.  All together, I believe they only add 282k to the image size but provide the ability for network connectivity testing.

**Comment by borrougagnou** [comment]
Hello,

Yes you are true,
I'll implement that in the next release

**Comment by borrougagnou** [comment]
okay, new release done :heavy_check_mark: 
everything is now updated.

Have a great day !
